version: '3'

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: account
      MYSQL_USER: account_admin
      MYSQL_PASSWORD: secret-admin
    ports:
      - "6060:3306"
    volumes:
      - ./sql/data/db:/var/lib/mysql
      - ./dump.sql:/sql/start.sql